# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b16ea2903b514c88901e7cc7263c2ab7e4d43d604ce661161fdbfe02988605bb8f05ca895b7ef146d591d7a247710a70b75c4172dc0e14fcb9c0ddcdce4bed1f

test:
  secret_key_base: 8813a4f16586fab1fd0a0139bd9426090f46240f52b0b8d63d389b8a0e49baffb63bbc9077fdfa0d802f2af371ae029c8d426bebb2a1846cbc10bf9d2f9acacd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
